// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           18
// Async Callback (empty):               1
// Total number of exported functions:  21

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    tcl_marketplace
    (
        init => init
        upgrade => upgrade
        listNFT => list_nft
        buyNFT => buy_nft
        cancelListing => cancel_listing
        updatePrice => update_price
        addAllowedCreator => add_allowed_creator
        removeAllowedCreator => remove_allowed_creator
        pause => pause
        unpause => unpause
        setFeePercent => set_fee_percent
        recoverTokens => recover_tokens
        getActiveListings => get_active_listings
        getListing => get_listing
        getListingCount => get_listing_count
        getFeePercent => get_fee_percent
        getTclToken => get_tcl_token
        getSellerListings => get_seller_listings
        isPaused => is_paused
        isCreatorAllowed => is_creator_allowed
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
