module.exports = {
  apps: [
    {
      name: "tcl-api",
      script: "server.js",
      cwd: "/opt/tcl-api",
      instances: 2,
      exec_mode: "cluster",
      watch: false,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
        PORT: 4000,
      },
      env_file: "/opt/tcl-api/.env",
      error_file: "/var/log/tcl-api-error.log",
      out_file: "/var/log/tcl-api-out.log",
      time: true,
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: "tcl-nft-sync",
      script: "/opt/tcl-api/sync-nfts.js",
      cwd: "/opt/tcl-api",
      instances: 1,
      exec_mode: "fork",
      watch: false,
      cron_restart: "*/15 * * * *",
      autorestart: false,
      env_file: "/opt/tcl-api/.env",
      error_file: "/root/.pm2/logs/tcl-nft-sync-error.log",
      out_file: "/root/.pm2/logs/tcl-nft-sync-out.log",
      time: true,
    },
    {
      name: "tcl-staking",
      script: "python3",
      args: "/opt/tcl-api/staking_indexer.py",
      cwd: "/opt/tcl-api",
      instances: 1,
      exec_mode: "fork",
      watch: false,
      cron_restart: "*/10 * * * *",
      autorestart: false,
      env_file: "/opt/tcl-api/.env",
      error_file: "/root/.pm2/logs/tcl-staking-error.log",
      out_file: "/root/.pm2/logs/tcl-staking-out.log",
      time: true,
    },
  ],
};
