# Generated by Django 5.0.6 on 2024-07-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tclWiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tex', models.TextField(max_length=2000)),
                ('image', models.FileField(upload_to='')),
                ('date_now', models.DateField()),
            ],
        ),
    ]