# Generated by Django 5.0.6 on 2024-07-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tclWiki', '0003_alter_date_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorsel', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
