# Generated by Django 5.0.6 on 2024-07-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tclWiki', '0004_resim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='tex',
            new_name='text',
        ),
    ]
