# Generated by Django 5.0.6 on 2024-07-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tclWiki', '0005_rename_tex_date_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='İmage'),
        ),
        migrations.AlterField(
            model_name='date',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='kingdomDetailText'),
        ),
        migrations.AlterField(
            model_name='date',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
