module.exports = {
  apps: [
    {
      name: "tcl-companion",
      script: "/opt/tcl-companion/venv/bin/uvicorn",
      args: "main:app --host 0.0.0.0 --port 8080 --workers 2 --loop uvloop",
      cwd: "/opt/tcl-companion",
      interpreter: "none",
      env: {
        OLLAMA_URL:         "http://localhost:11434",
        OLLAMA_MODEL:       "qwen2.5:14b",
        OLLAMA_EMBED_MODEL: "nomic-embed-text",
        QDRANT_URL:         "http://localhost:6333",
        QDRANT_COLLECTION:  "tcl_knowledge",
        ALLOWED_ORIGINS:    "https://tclexplorer.com,https://axel4ro.github.io",
        SYNC_SECRET:        "SCHIMBA_CU_UN_SECRET_RANDOM",
        RAG_MATCH_COUNT:    "6",
        CHUNK_SIZE:         "1400",
        CHUNK_OVERLAP:      "220",
      },
      max_memory_restart: "4G",
      error_file: "/opt/tcl-companion/logs/err.log",
      out_file:   "/opt/tcl-companion/logs/out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      restart_delay: 3000,
      watch: false,
    },
    {
      name: "tcl-dynamic-data",
      script: "/opt/tcl-companion/venv/bin/python3",
      args: "dynamic_fetcher.py",
      cwd: "/opt/tcl-companion",
      interpreter: "none",
      cron_restart: "*/5 * * * *",
      autorestart: false,
      env: {
        DYNAMIC_JSON_PATH: "/opt/tcl-companion/data/dynamic.json",
      },
      error_file: "/opt/tcl-companion/logs/dynamic_err.log",
      out_file:   "/opt/tcl-companion/logs/dynamic_out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
  ],
};
